### PR TITLE
Fix device-specific logic in install script

### LINKED ISSUE #6390: [Bug]: bug in device-install.sh
### Category

Other

### Hardware

Heltec V3

### Is this bug report about any UI component firmware like InkHUD or Meshtatic UI (MUI)?

- [ ] Meshtastic UI aka MUI colorTFT
- [ ] InkHUD ePaper
- [ ] OLED slide UI on any display

### Firmware Version

2.6.2.31c0e8f

### Description

There is a bug with matching a portion of the filename with a construct like if [ -n "${FILENAME##*"$variant"*}" ]
This evaluates to true at least on recent Debian 12.9 which uses bash version 5.2.15(1)-release (x86_64-pc-linux-gnu). To check just put an echo statement in the if-s and see how much times they match. Also please check the log output with incorrect addresses for an 8MB heltec v3.

I'm attaching a fixed version [device-install.sh.txt](https://github.com/user-attachments/files/19438378/device-install.sh.txt)

This is the diff:

```
--- device-install.sh.orig      2025-03-20 21:59:02.000000000 +0100
+++ device-install.sh   2025-03-24 22:16:27.661217168 +0100
@@ -138,7 +138,7 @@
 
        # littlefs* offset for BigDB 8mb and OTA OFFSET.
        for variant in "${BIGDB_8MB[@]}"; do
-               if [ -n "${FILENAME##*"$variant"*}" ]; then
+               if [[ "${FILENAME}" == *"${variant}"* ]]; then
                        OFFSET=0x670000
                        OTA_OFFSET=0x340000


                fi
@@ -146,7 +146,7 @@
 
        # littlefs* offset for BigDB 16mb and OTA OFFSET.
        for variant in "${BIGDB_16MB[@]}"; do
-               if [ -n "${FILENAME##*"$variant"*}" ]; then
+               if [[ "${FILENAME}" == *"${variant}"* ]]; then
                        OFFSET=0xc90000
                        OTA_OFFSET=0x650000
                fi
@@ -155,13 +155,13 @@
        # Account for S3 board's different OTA partition
        # FIXME: Use PlatformIO info to determine MCU type, this is unmaintainable
        for variant in "${S3_VARIANTS[@]}"; do
-               if [ -n "${FILENAME##*"$variant"*}" ]; then
+               if [[ "${FILENAME}" == *"${variant}"* ]]; then
                        MCU="esp32s3"
                fi
        done
 
        if [ "$MCU" != "esp32s3" ]; then
-               if [ -n "${FILENAME##*"esp32c3"*}" ]; then
+               if [[ "${FILENAME}" == *esp32c3* ]]; then
                        OTAFILE=bleota.bin
                else
                        OTAFILE=bleota-c3.bin
```

Note: i would just send you a pull request if not for the CLA which is not understandable by many developers including me (but this ticket it not for discussion about this, so please don't). I'm fine with the terms of the GPL

### Relevant log output

```Shell
(venv1_meshtastic) sq5bpf@chronos:~/meshtastic/firmware-esp32s3-2.6.2$ ./device-install.sh -f firmware-heltec-v3-2.6.2.31c0e8f.bin 
Trying to flash firmware-heltec-v3-2.6.2.31c0e8f.bin, but first erasing and writing system information
esptool.py v4.7.0
Found 1 serial ports
Serial port /dev/ttyUSB0
Connecting....
Detecting chip type... ESP32-S3
Chip is ESP32-S3 (QFN56) (revision v0.2)
Features: WiFi, BLE, Embedded Flash 8MB (GD)
Crystal is 40MHz
MAC: 34:cd:b0:xx:yy:zz
Uploading stub...
Running stub...
Stub running...
Erasing flash (this may take a while)...
Chip erase completed successfully in 3.2s
Hard resetting via RTS pin...
esptool.py v4.7.0
Found 1 serial ports
Serial port /dev/ttyUSB0
Connecting....
Detecting chip type... ESP32-S3
Chip is ESP32-S3 (QFN56) (revision v0.2)
Features: WiFi, BLE, Embedded Flash 8MB (GD)
Crystal is 40MHz
MAC: 34:cd:b0:xx:yy:zz
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Flash will be erased from 0x00000000 to 0x001defff...
Compressed 1961104 bytes to 1209425...
Wrote 1961104 bytes (1209425 compressed) at 0x00000000 in 106.8 seconds (effective 146.9 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
Trying to flash bleota-s3.bin at offset 0x650000
esptool.py v4.7.0
Found 1 serial ports
Serial port /dev/ttyUSB0
Connecting....
Detecting chip type... ESP32-S3
Chip is ESP32-S3 (QFN56) (revision v0.2)
Features: WiFi, BLE, Embedded Flash 8MB (GD)
Crystal is 40MHz
MAC: 34:cd:b0:xx:yy:zz
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Flash will be erased from 0x00650000 to 0x006cbfff...
Compressed 506704 bytes to 309041...
Wrote 506704 bytes (309041 compressed) at 0x00650000 in 27.4 seconds (effective 147.8 kbit/s)...
Hash of data verified.
Leaving...
Hard resetting via RTS pin...
Trying to flash littlefs-heltec-v3-2.6.2.31c0e8f.bin, at offset 0xc90000
esptool.py v4.7.0
Found 1 serial ports
Serial port /dev/ttyUSB0
Connecting....
Detecting chip type... ESP32-S3
Chip is ESP32-S3 (QFN56) (revision v0.2)
Features: WiFi, BLE, Embedded Flash 8MB (GD)
Crystal is 40MHz
MAC: 34:cd:b0:xx:yy:zz
Uploading stub...
Running stub...
Stub running...
Configuring flash size...

A fatal error occurred: File littlefs-heltec-v3-2.6.2.31c0e8f.bin (length 1572864) at offset 13172736 will not fit in 8388608 bytes of flash. Use --flash_size argument, or change flashing address.
```

### PR DESCRIPTION
**Pull request by epall**
These new for loops to check for variants in a list should be checking for the string to _be empty_, not _non-empty_, if a match is found causing the replacement to fire.

Tested locally with Heltec V3

Fixes #6390.

## 🤝 Attestations
- [x] I have tested that my proposed changes behave as described.
- [x] I have tested that my proposed changes do not cause any obvious regressions on the following devices:
  - [x] Heltec (Lora32) V3
  - [ ] LilyGo T-Deck 
  - [ ] LilyGo T-Beam
  - [ ] RAK WisBlock 4631
  - [ ] Seeed Studio T-1000E tracker card
  - [ ] Other (please specify below)

### CODE REVIEW

File: bin/device-install.sh [hunk 1]
```diff
@@ -138,15 +138,15 @@ if [ -f "${FILENAME}" ] && [ -n "${FILENAME##*"update"*}" ]; then
 
 	# littlefs* offset for BigDB 8mb and OTA OFFSET.
 	for variant in "${BIGDB_8MB[@]}"; do
-		if [ -n "${FILENAME##*"$variant"*}" ]; then
+		if [ ! -n "${FILENAME##*"$variant"*}" ]; then
```
Comment (jedahan) [inline bin/device-install.sh:141]: I *think* this is equivalent:

```suggestion
		if [ -z "${FILENAME##*"$variant"*}" ]; then
```

Comment (jedahan) [reply bin/device-install.sh:141]: This will be true if empty string, or if the variable is unset
