### PR TITLE
T-Lora Pager: Support LR1121 and SX1280 models

### LINKED ISSUE #7950: [Bug]: T-Lora Pager LR1121 'Critical fault #3' and crashes
### Category

Hardware Compatibility

### Hardware

T-Lora Pager with LR1121

### Is this bug report about any UI component firmware like InkHUD or Meshtatic UI (MUI)?

- [ ] Meshtastic UI aka MUI colorTFT
- [ ] InkHUD ePaper
- [ ] OLED slide UI on any display

### Firmware Version

2.7.9.6f7149e (latest develop branch at time of writing)

### Description

Upon booting T-Lora Pager I am faced with `Critical fault #3`:

Image

<br>

<br>

I am mostly able to scroll through the different tabs using the rotary encoder, though it often snaps back to the first tab which contains the critical fault message. It also sometimes snaps back to the messages tab.

Attempting to open the tab with the "wifi" icon crashes and reboots the device.

Pressing the spacebar and the "option?" key (the orange one in bottom left) will vibrate and snap back to the critical fault tab, from then on the rotary encoder stops working to switch tab making the device unusable until a reboot (though it keeps vibrating on press of spacebar and option keys).

I have tested `2.7.7.5ae4ff9`, `2.7.8.a0c0388` and latest develop branch `2.7.9.6f7149e`, all of these exhibit all these same exact issues. The only noticeable difference is latest develop branch is slightly better with rotary encoder switching tab, though still not great.

### I assume this is related to my device using an LR1121 chip instead of an SX1262 chip

From what I could tell no one else has noticed these issues yet, and the more popular configurations seem with SX1262 (the shop page features the 3 base options, 433mhz / 868mhz / 915mhz, which are all SX1262, there is only one option for LR1121).

I am unable to confirm whether LoRa is even working as this is the only LoRa device I have and no one I know close to me owns a Meshtastic node. I bought the device to get into Meshtastic and use it at cons, and possibly discover other nodes nearby, so yeah I am unable to tell if it's working as I don't have a reference point to compare with.

### Relevant log output

```Shell

```

### PR DESCRIPTION
**Pull request by WillyJL**
Fixes #7950.

Unable to test SX1280 model as I do not have one. I am new to Meshtastic so I haven't done extensive testing, but it seems to atleast work fine now on my LR1121 model.

No more `Critical fault #3`, I can see channel utilization, open the LoRa info tab, and send messages both from device and app (unable to test if they get received, I don't have any other nodes yet).

## 🤝 Attestations

- [x] I have tested that my proposed changes behave as described.
- [ ] I have tested that my proposed changes do not cause any obvious regressions on the following devices:
  - [ ] Heltec (Lora32) V3
  - [ ] LilyGo T-Deck
  - [ ] LilyGo T-Beam
  - [ ] RAK WisBlock 4631
  - [ ] Seeed Studio T-1000E tracker card
  - [ ] Other (please specify below)
    - [x] T-Lora Pager LR1121

### CODE REVIEW

File: variants/esp32s3/tlora-pager/variant.h [hunk 1]
```diff
@@ -105,21 +105,44 @@
...
 #define LORA_CS 36
+#define LORA_RESET 47
 
 #define LORA_DIO0 -1 // a No connect on the SX1262 module
-#define LORA_RESET 47
 #define LORA_DIO1 14 // SX1262 IRQ
 #define LORA_DIO2 48 // SX1262 BUSY
 #define LORA_DIO3    // Not connected on PCB, but internally on the TTGO SX1262, if DIO3 is high the TXCO is enabled
 
+#ifdef USE_SX1262
```
Comment (mverch67) [inline variants/esp32s3/tlora-pager/variant.h]: you killed the SX1268

**Comment by WillyJL** [comment]
Confirmed working on T-Lora Pager SX1262 model too by a friend, so no regressions there.

I also got a Heltec v3 today as a second node for testing, and can confirm T-Lora Pager LR1121 can send and receive very well with this patch.

**Comment by mverch67** [comment]
> Confirmed working on T-Lora Pager SX1262 model too by a friend, so no regressions there.
> 
> I also got a Heltec v3 today as a second node for testing, and can confirm T-Lora Pager LR1121 can send and receive very well with this patch.

I'm just asking to remove the #ifdefs SX12XY in the variant file, as this is (a) not required and (b) not in line with the existing other variant files and (c) confusing for SX1268 owners).

**Comment by WillyJL** [comment]
> > Confirmed working on T-Lora Pager SX1262 model too by a friend, so no regressions there.
> > I also got a Heltec v3 today as a second node for testing, and can confirm T-Lora Pager LR1121 can send and receive very well with this patch.
> 
> I'm just asking to remove the #ifdefs SX12XY in the variant file, as this is (a) not required and (b) not in line with the existing other variant files and (c) confusing for SX1268 owners).

I added them as it seemed like this is how most other variants do it: 3 of 4 other lr1121 variants use ifdefs, 10 of 14 sx1280 use ifdefs, and i didnt count for sx1262 but some do some dont. i guess maybe they were added with the intention of being easy to disable by removing the define, but the pins being defined doesnt matter anyway if the use define is missing so it doesnt make much difference, ill remove them

File: variants/esp32s3/tlora-pager/variant.h (hunk 1 above)
Comment (WillyJL) [reply variants/esp32s3/tlora-pager/variant.h]: aha forgot to submit the review, i couldnt this comment until now :wink: happens to me too at times

**Review by thebentern — APPROVED** [review]

**Comment by benjamincarmel** [comment]
WillyJ I hope you keep contributing to the pager :)

**Comment by WillyJL** [comment]
> WillyJ I hope you keep contributing to the pager :)

i have a few PRs open that fix the last few things iffy with it,other than that i dont see what else there is to do, besides MUI support which is a bit too much for me
