### PR TITLE
[esp32] Define BUTTON_PIN (-1) by default, fixes #6213

### LINKED ISSUE #6213: [Bug]: GPIO incorrect for Lilygo Lora32 2.1 1.6.1
### Category

Other

### Hardware

T-Lora v2 1.6

### Firmware Version

2.5.20 (latest beta)

### Description

have connected a switch across IO12 and GND as per doc, however this doesn't appear to have any effect as a user button. Continuity and circuit both checked. Am currently checking code for this board to see where the GPIO is configured...

PIN_BUTTON defined as '12' in Device Config (Android app)

### Relevant log output

```Shell

```

### PR DESCRIPTION
**Pull request by ndoo**
ESP32 - Define BUTTON_PIN (-1) by default, fixes #6213 because button setup is always done in https://github.com/meshtastic/firmware/blob/1e4a0134e6ed6d455e54cd21f64232389280781b/src/main.cpp#L375-L392 and https://github.com/meshtastic/firmware/blob/1e4a0134e6ed6d455e54cd21f64232389280781b/src/ButtonThread.cpp#L31-L58 when the user preference for button pin is configured.

### CODE REVIEW

File: src/platform/esp32/architecture.h [hunk 1]
```diff
@@ -53,6 +53,8 @@
 #ifdef PIN_BUTTON_TOUCH
 #define BUTTON_PIN_TOUCH PIN_BUTTON_TOUCH
 #endif
+
+#define BUTTON_PIN (-1)
 //
```
Comment (caveman99) [inline src/platform/esp32/architecture.h:58]: This woud belong in configuration.h and urgently with a check if it is not already set.

**Review by caveman99 — CHANGES_REQUESTED** [review]

File: src/platform/esp32/architecture.h (hunk 1 above)
Comment (ndoo) [reply src/platform/esp32/architecture.h]: Moved, rebased commit on top of master HEAD and force-pushed my branch.

**Comment by ndoo** [comment]
I only compile-tested the above change, would appreciate if anyone with access to a T-LoRa V2.1 1.6 could try it out, I will functionality-test it tomorrow otherwise (my hardware is in the office).

**Review by caveman99 — APPROVED** [review]

**Comment by ndoo** [comment]
Hmm, is there some reason this isn’t being done in the variant files for
nrf52? Or if it is, can this be safely gated behind an #ifndef (or is it
even needed?)
